/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const aboutPage: string;
const aboutImg: string;
const explore: string;
const aboutButton: string;

export {
	aboutPage as "about-page",
	aboutPage,
	aboutImg as "about-img",
	aboutImg,
	explore,
	aboutButton as "about-button",
	aboutButton
};

export default {
	"about-page": aboutPage,
	aboutPage,
	"about-img": aboutImg,
	aboutImg,
	explore,
	"about-button": aboutButton,
	aboutButton
};
