/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const dashboard: string;
const information: string;
const dashboardWelcome: string;
const informationContent: string;
const reviews: string;
const income: string;
const vansListHeader: string;
const detailsContainer: string;
const details: string;

export {
	dashboard,
	information,
	dashboardWelcome as "dashboard-welcome",
	dashboardWelcome,
	informationContent as "information-content",
	informationContent,
	reviews,
	income,
	vansListHeader as "vans-list-header",
	vansListHeader,
	detailsContainer as "details-container",
	detailsContainer,
	details
};

export default {
	dashboard,
	information,
	"dashboard-welcome": dashboardWelcome,
	dashboardWelcome,
	"information-content": informationContent,
	informationContent,
	reviews,
	income,
	"vans-list-header": vansListHeader,
	vansListHeader,
	"details-container": detailsContainer,
	detailsContainer,
	details
};
