/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const dashboard: string;
const information: string;
const dashboardWelcome: string;
const informationContent: string;
const reviews: string;
const income: string;
const vansListHeader: string;
const detailsContainer: string;
const details: string;
const incomeContainer: string;
const incomeTransactions: string;
const incomeTransactionsHeader: string;
const transaction: string;

export {
	dashboard,
	information,
	dashboardWelcome as "dashboard-welcome",
	dashboardWelcome,
	informationContent as "information-content",
	informationContent,
	reviews,
	income,
	vansListHeader as "vans-list-header",
	vansListHeader,
	detailsContainer as "details-container",
	detailsContainer,
	details,
	incomeContainer as "income-container",
	incomeContainer,
	incomeTransactions as "income-transactions",
	incomeTransactions,
	incomeTransactionsHeader as "income-transactions-header",
	incomeTransactionsHeader,
	transaction
};

export default {
	dashboard,
	information,
	"dashboard-welcome": dashboardWelcome,
	dashboardWelcome,
	"information-content": informationContent,
	informationContent,
	reviews,
	income,
	"vans-list-header": vansListHeader,
	vansListHeader,
	"details-container": detailsContainer,
	detailsContainer,
	details,
	"income-container": incomeContainer,
	incomeContainer,
	"income-transactions": incomeTransactions,
	incomeTransactions,
	"income-transactions-header": incomeTransactionsHeader,
	incomeTransactionsHeader,
	transaction
};
