/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const title: string;
const nav: string;

export {
	title,
	nav
};

export default {
	title,
	nav
};
