/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const hostVansOverview: string;
const hostVansEntry: string;
const hostVansImg: string;
const hostVansEntryCol: string;
const hostVansEntryLink: string;
const perDayText: string;

export {
	hostVansOverview as "host-vans-overview",
	hostVansOverview,
	hostVansEntry as "host-vans-entry",
	hostVansEntry,
	hostVansImg as "host-vans-img",
	hostVansImg,
	hostVansEntryCol as "host-vans-entry-col",
	hostVansEntryCol,
	hostVansEntryLink as "host-vans-entry-link",
	hostVansEntryLink,
	perDayText as "per-day-text",
	perDayText
};

export default {
	"host-vans-overview": hostVansOverview,
	hostVansOverview,
	"host-vans-entry": hostVansEntry,
	hostVansEntry,
	"host-vans-img": hostVansImg,
	hostVansImg,
	"host-vans-entry-col": hostVansEntryCol,
	hostVansEntryCol,
	"host-vans-entry-link": hostVansEntryLink,
	hostVansEntryLink,
	"per-day-text": perDayText,
	perDayText
};
