/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const vanDetailDetails: string;
const vanDetailDetailsTop: string;
const vanDetailDetailsTopSide: string;
const vanDetailDetailsImg: string;
const vanDetailDetailsH2: string;
const vanDetailDetailsBottom: string;
const hostNav: string;
const photosFlex: string;
const photosFlexPhoto: string;
const vanDetailPage: string;
const back: string;
const linkBack: string;
const perDayText: string;

export {
	vanDetailDetails as "van-detail-details",
	vanDetailDetails,
	vanDetailDetailsTop as "van-detail-details-top",
	vanDetailDetailsTop,
	vanDetailDetailsTopSide as "van-detail-details-top-side",
	vanDetailDetailsTopSide,
	vanDetailDetailsImg as "van-detail-details-img",
	vanDetailDetailsImg,
	vanDetailDetailsH2 as "van-detail-details-h2",
	vanDetailDetailsH2,
	vanDetailDetailsBottom as "van-detail-details-bottom",
	vanDetailDetailsBottom,
	hostNav as "host-nav",
	hostNav,
	photosFlex as "photos-flex",
	photosFlex,
	photosFlexPhoto as "photos-flex-photo",
	photosFlexPhoto,
	vanDetailPage as "van-detail-page",
	vanDetailPage,
	back,
	linkBack as "link-back",
	linkBack,
	perDayText as "per-day-text",
	perDayText
};

export default {
	"van-detail-details": vanDetailDetails,
	vanDetailDetails,
	"van-detail-details-top": vanDetailDetailsTop,
	vanDetailDetailsTop,
	"van-detail-details-top-side": vanDetailDetailsTopSide,
	vanDetailDetailsTopSide,
	"van-detail-details-img": vanDetailDetailsImg,
	vanDetailDetailsImg,
	"van-detail-details-h2": vanDetailDetailsH2,
	vanDetailDetailsH2,
	"van-detail-details-bottom": vanDetailDetailsBottom,
	vanDetailDetailsBottom,
	"host-nav": hostNav,
	hostNav,
	"photos-flex": photosFlex,
	photosFlex,
	"photos-flex-photo": photosFlexPhoto,
	photosFlexPhoto,
	"van-detail-page": vanDetailPage,
	vanDetailPage,
	back,
	"link-back": linkBack,
	linkBack,
	"per-day-text": perDayText,
	perDayText
};
