/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const title: string;
const nav: string;
const copyrightText: string;

export {
	title,
	nav,
	copyrightText as "copyright-text",
	copyrightText
};

export default {
	title,
	nav,
	"copyright-text": copyrightText,
	copyrightText
};
