/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const loginContainer: string;
const loginForm: string;
const loginButton: string;

export {
	loginContainer as "login-container",
	loginContainer,
	loginForm as "login-form",
	loginForm,
	loginButton as "login-button",
	loginButton
};

export default {
	"login-container": loginContainer,
	loginContainer,
	"login-form": loginForm,
	loginForm,
	"login-button": loginButton,
	loginButton
};
