/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const mainPage: string;
const header: string;

export {
	mainPage as "main-page",
	mainPage,
	header
};

export default {
	"main-page": mainPage,
	mainPage,
	header
};
