/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const mainPage: string;
const header: string;
const mainButton: string;
const orangeButton: string;

export {
	mainPage as "main-page",
	mainPage,
	header,
	mainButton as "main-button",
	mainButton,
	orangeButton as "orange-button",
	orangeButton
};

export default {
	"main-page": mainPage,
	mainPage,
	header,
	"main-button": mainButton,
	mainButton,
	"orange-button": orangeButton,
	orangeButton
};
