/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const modalContainer: string;
const modalContent: string;

export {
	modalContainer as "modal-container",
	modalContainer,
	modalContent as "modal-content",
	modalContent
};

export default {
	"modal-container": modalContainer,
	modalContainer,
	"modal-content": modalContent,
	modalContent
};
