/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const notfoundPage: string;
const backButton: string;

export {
	notfoundPage as "notfound-page",
	notfoundPage,
	backButton as "back-button",
	backButton
};

export default {
	"notfound-page": notfoundPage,
	notfoundPage,
	"back-button": backButton,
	backButton
};
