/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const reviewContainer: string;
const topbar: string;
const reviewSummary: string;
const reviewSummaryTitle: string;
const reviewSummaryGraphic: string;
const reviewContent: string;
const reviewGraphic: string;
const reviewTitleBar: string;
const reviewParagraph: string;
const stars: string;

export {
	reviewContainer as "review-container",
	reviewContainer,
	topbar,
	reviewSummary as "review-summary",
	reviewSummary,
	reviewSummaryTitle as "review-summary-title",
	reviewSummaryTitle,
	reviewSummaryGraphic as "review-summary-graphic",
	reviewSummaryGraphic,
	reviewContent as "review-content",
	reviewContent,
	reviewGraphic as "review-graphic",
	reviewGraphic,
	reviewTitleBar as "review-title-bar",
	reviewTitleBar,
	reviewParagraph as "review-paragraph",
	reviewParagraph,
	stars
};

export default {
	"review-container": reviewContainer,
	reviewContainer,
	topbar,
	"review-summary": reviewSummary,
	reviewSummary,
	"review-summary-title": reviewSummaryTitle,
	reviewSummaryTitle,
	"review-summary-graphic": reviewSummaryGraphic,
	reviewSummaryGraphic,
	"review-content": reviewContent,
	reviewContent,
	"review-graphic": reviewGraphic,
	reviewGraphic,
	"review-title-bar": reviewTitleBar,
	reviewTitleBar,
	"review-paragraph": reviewParagraph,
	reviewParagraph,
	stars
};
