/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const vanDetailContainer: string;
const back: string;
const vanDetail: string;
const vanPrice: string;
const linkButton: string;
const vantypeany: string;
const backFlex: string;

export {
	vanDetailContainer as "van-detail-container",
	vanDetailContainer,
	back,
	vanDetail as "van-detail",
	vanDetail,
	vanPrice as "van-price",
	vanPrice,
	linkButton as "link-button",
	linkButton,
	vantypeany,
	backFlex as "back-flex",
	backFlex
};

export default {
	"van-detail-container": vanDetailContainer,
	vanDetailContainer,
	back,
	"van-detail": vanDetail,
	vanDetail,
	"van-price": vanPrice,
	vanPrice,
	"link-button": linkButton,
	linkButton,
	vantypeany,
	"back-flex": backFlex,
	backFlex
};
