/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const options: string;
const vanPage: string;
const vanFilter: string;
const vanFilterClear: string;
const optionsContainer: string;
const optionsImg: string;
const optionsSubcomponent: string;
const vanText: string;
const dayText: string;

export {
	options,
	vanPage as "van-page",
	vanPage,
	vanFilter as "van-filter",
	vanFilter,
	vanFilterClear as "van-filter-clear",
	vanFilterClear,
	optionsContainer as "options-container",
	optionsContainer,
	optionsImg as "options-img",
	optionsImg,
	optionsSubcomponent as "options-subcomponent",
	optionsSubcomponent,
	vanText as "van-text",
	vanText,
	dayText as "day-text",
	dayText
};

export default {
	options,
	"van-page": vanPage,
	vanPage,
	"van-filter": vanFilter,
	vanFilter,
	"van-filter-clear": vanFilterClear,
	vanFilterClear,
	"options-container": optionsContainer,
	optionsContainer,
	"options-img": optionsImg,
	optionsImg,
	"options-subcomponent": optionsSubcomponent,
	optionsSubcomponent,
	"van-text": vanText,
	vanText,
	"day-text": dayText,
	dayText
};
